# Generated by Django 5.2.12 on 2026-03-28 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_read_later', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='rssapp.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'updated_at'], name='rssapp_arti_user_id_2cef78_idx'), models.Index(fields=['user', 'is_read_later'], name='rssapp_arti_user_id_d1de33_idx'), models.Index(fields=['user', 'is_favorite'], name='rssapp_arti_user_id_a28ea4_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='uniq_article_user_state')],
            },
        ),
    ]
