# Generated by Django 5.2.12 on 2026-03-28 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rssapp", "0002_articleuserstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="feed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="rssapp.feed",
            ),
        ),
    ]
