# Generated by Django 5.2.12 on 2026-03-28 12:03

from django.db import migrations, models


def backfill_display_order(apps, schema_editor):
    Feed = apps.get_model("rssapp", "Feed")
    for order, feed in enumerate(Feed.objects.order_by("id").iterator(), start=1):
        feed.display_order = order
        feed.save(update_fields=["display_order"])


class Migration(migrations.Migration):
    dependencies = [
        ("rssapp", "0003_article_feed"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="feed",
            name="category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="feed",
            name="display_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="feed",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(backfill_display_order, migrations.RunPython.noop),
    ]
