# Generated by Django 5.2.12 on 2026-03-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0005_tag_bookmark_tag_uniq_user_tag_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
