# Generated by Django 5.2.12 on 2026-03-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0007_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
