# Generated by Django 5.2.12 on 2026-05-08 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0015_remove_is_favorite_from_userstates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articleuserstate',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bookmarkuserstate',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='articleuserstate',
            index=models.Index(fields=['user', 'is_favorite'], name='rssapp_arti_user_id_a28ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkuserstate',
            index=models.Index(fields=['user', 'is_favorite'], name='rssapp_book_user_id_d9b094_idx'),
        ),
    ]
