# Generated by Django 5.2.14 on 2026-05-08 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0016_add_is_favorite_to_user_states'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': '記事', 'verbose_name_plural': '記事'},
        ),
        migrations.AlterModelOptions(
            name='articleuserstate',
            options={'verbose_name': '記事ユーザー状態', 'verbose_name_plural': '記事ユーザー状態'},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at'], 'verbose_name': 'ブックマーク', 'verbose_name_plural': 'ブックマーク'},
        ),
        migrations.AlterModelOptions(
            name='bookmarkcategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'ブックマークカテゴリ', 'verbose_name_plural': 'ブックマークカテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='bookmarkuserstate',
            options={'verbose_name': 'ブックマークユーザー状態', 'verbose_name_plural': 'ブックマークユーザー状態'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='extractiontask',
            options={'ordering': ['created_at'], 'verbose_name': '抽出タスク', 'verbose_name_plural': '抽出タスク'},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name': 'フィード', 'verbose_name_plural': 'フィード'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'タグ', 'verbose_name_plural': 'タグ'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'ユーザープロフィール', 'verbose_name_plural': 'ユーザープロフィール'},
        ),
        migrations.AddField(
            model_name='bookmarkcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rssapp.bookmarkcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rssapp.category'),
        ),
        migrations.AlterField(
            model_name='bookmarkcategory',
            name='color',
            field=models.CharField(choices=[('#EF4444', 'Red'), ('#F97316', 'Orange'), ('#EAB308', 'Yellow'), ('#22C55E', 'Green'), ('#14B8A6', 'Teal'), ('#3B82F6', 'Blue'), ('#6366F1', 'Indigo'), ('#8B5CF6', 'Violet'), ('#EC4899', 'Pink'), ('#6B7280', 'Gray'), ('#78716C', 'Stone'), ('#0EA5E9', 'Sky')], default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#EF4444', 'Red'), ('#F97316', 'Orange'), ('#EAB308', 'Yellow'), ('#22C55E', 'Green'), ('#14B8A6', 'Teal'), ('#3B82F6', 'Blue'), ('#6366F1', 'Indigo'), ('#8B5CF6', 'Violet'), ('#EC4899', 'Pink'), ('#6B7280', 'Gray'), ('#78716C', 'Stone'), ('#0EA5E9', 'Sky')], default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#EF4444', 'Red'), ('#F97316', 'Orange'), ('#EAB308', 'Yellow'), ('#22C55E', 'Green'), ('#14B8A6', 'Teal'), ('#3B82F6', 'Blue'), ('#6366F1', 'Indigo'), ('#8B5CF6', 'Violet'), ('#EC4899', 'Pink'), ('#6B7280', 'Gray'), ('#78716C', 'Stone'), ('#0EA5E9', 'Sky')], default='#3B82F6', max_length=7),
        ),
    ]
