# Generated by Django 5.2.14 on 2026-05-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0017_category_hierarchy_and_color_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this feed is publicly visible (for future sharing features)'),
        ),
    ]
